### ISSUE TITLE
Bootstrap SCSS and custom.scss

### ISSUE THREAD

**Issue by sinklair** [creativetimofficial/ct-paper-kit-2-pro#15]
The UI Kit distribution uses included bootstrap CSS files. This means that a lot of styles are hard-coded into CSS files that makes it hard to override some basic color and style information.

Is there a way to get the UI kit default bootstrap SCSS along with the custom.scss that you have applied so that we can override without having to manually search CSS files?

**Comment by sinklair** [comment]
Any update here?

**Comment by barak-neeman** [comment]
+1
I think getting access to the custom.scss that creativetim uses will really help

**Comment by groovemen** [comment]
Hello @sinklair,

Thank you for using our products, you can find the SCSS file on Bootstrap's Github repo. Please visit the following [link](https://github.com/twbs/bootstrap/tree/v4-dev/scss) and try to integrate it into your project.

Best, 
Stefan

**Comment by sinklair** [comment]
@groovemen we actually are talking about the custom scss that creative tim used on those files. Right now the distribution includes only the output of those scss files and your custom overrides.

**Comment by groovemen** [comment]
@sinklair, the styles that are hard-coded into CSS come from a SASS that is structured for each component from the UI kit. And if you also check the **assets/scss/paper-kit.scss** you'll see how we imported each style for every component, plugins and so on. If you'll replace a specific import, for example `@import 'paper-dashboard/buttons';` with the bootstrap's style, you'll get what you need.
