### ISSUE TITLE
How to activate Pricing Toggle

### ISSUE THREAD

**Issue by ASGrant55** [creativetimofficial/ct-paper-kit-2-pro#19]
I want to use "Pricing 2" from your sections.html example but I don't see any documentation on ways to activate the "monthly" vs "yearly" pricing in the price card.

**Comment by groovemen** [comment]
Hello @ASGrant55, 

Thank you for your interest in working with our products, I will ask you to check the pricing-5 section, you have an example of how you can switch beside "personal" and "commercial" and you have to integrate into your monthly and yearly pricing plan the `nav-pills`.

<img width="1440" alt="screenshot 2018-11-07 at 13 04 08" src="https://user-images.githubusercontent.com/21063398/48128122-3491bd80-e28e-11e8-806e-5a96f4b1e221.png">
<img width="1440" alt="screenshot 2018-11-07 at 13 04 15" src="https://user-images.githubusercontent.com/21063398/48128132-39567180-e28e-11e8-85fe-ef776e5de2c5.png">

All the best, 
Stefan
