### ISSUE TITLE
Datetimepicker not working, nothing come out after clicking on the calendar icon

### ISSUE THREAD

**Issue by chongmandick** [creativetimofficial/ct-paper-kit-2-pro#2]
![screen shot 2018-01-30 at 6 20 08 pm](https://user-images.githubusercontent.com/35955783/35561221-90a5025c-05ea-11e8-8e1b-226dbb47e820.png)

**Comment by chongmandick** [comment]
![screen shot 2018-01-30 at 6 23 22 pm](https://user-images.githubusercontent.com/35955783/35561269-b76ba706-05ea-11e8-8c46-7fda80a57cc4.png)

**Comment by groovemen** [comment]
Hello @chongmandick, thank you for using our product. Moment JS library should be placed before the bootstrap-datepicker. Best, Stefan

**Comment by chongmandick** [comment]
Thanks, it now work when I click into the textbox.  But the calendar did not show up when I click the calendar icon...I wonder it may be browser-related because I am using Safari for Mac.
