### ISSUE TITLE
Default pagination style should match Button default style

### ISSUE THREAD

**Issue by maxtorete** [creativetimofficial/ct-paper-kit-2-pro#22]
Hi!

The default pagination clash with the danger one, as the two are identical with orange themed numbers. So I think the default pagination style should match de default button style, with dark borders and numbers. I will overwrite them in my site, but I would like to know if this will be fixed in future releases.

Best regards,
Juan

**Comment by groovemen** [comment]
Hello @maxtorete, 

Thank you for using our products and for letting us know about this issue, we will fix this issue in the next update; sorry for the inconvenience. 
*Please let us know if we can help you with anything else.

All the best,
