### ISSUE TITLE
Minification issue

### ISSUE THREAD

**Issue by z8rasmus** [creativetimofficial/ct-paper-kit-2-pro#24]
Hi,
I'm having issues when I use the minified version of the paper-kit.min.css.
This is the error I get i my browser:
/* Minification failed. Returning unminified contents.
(25,69120): run-time error CSS1062: Expected semicolon or closing curly-brace, found '0%'
(25,69210): run-time error CSS1062: Expected semicolon or closing curly-brace, found '0%'
(25,69294): run-time error CSS1062: Expected semicolon or closing curly-brace, found '0%'
 */
/*!

This issue originates in the file "_nucleo-icons.scss" - in the "Spinning Icons"-section.
When this file is minified the @-webkit-keyframes, @-moz-keyframe and @keyframes are removed.

What can I do to prevent this error?

Best regards
Rasmus

**Comment by groovemen** [comment]
Hello @z8rasmus,

Thank you for using our products, I tried the minified version (**paper-kit.min.css**) from the downloaded archive and everything looks good even on Firefox the Spinning Icons works and there are no errors in the console even if the **@-webkit-keyframes**, **@-moz-keyframe** and **@Keyframes** are removed

Best, 
Stefan
