### ISSUE TITLE
Directory structure is not the same as the documentation

### ISSUE THREAD

**Issue by nkabram** [creativetimofficial/ct-paper-kit-2-pro#25]
Missing documentation and missing css files. Can't get this to load. It seems as though the documentation is for Paper kit original not paper kit 2 or something. I don't have nucleo-icons.css for example. No where to be found in the downloaded bundle. Its so mixed up I don't even know how to straighten it out. 

Example missing in console: 

GET http://127.0.0.1:8000/static/assets/css/nucleo-icons.css net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:20 GET http://127.0.0.1:8000/static/assets/css/kit-pro.css net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:114 GET http://127.0.0.1:8000/static/assets/js/plugins/nouislider.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:123 GET http://127.0.0.1:8000/static/assets/js/plugins/bootstrap-datetimepicker.min.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:126 GET http://127.0.0.1:8000/static/assets/js/photo_swipe/photoswipe.min.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:127 GET http://127.0.0.1:8000/static/assets/js/photo_swipe/photoswipe-ui-default.min.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:128 GET http://127.0.0.1:8000/static/assets/js/photo_swipe/init-gallery.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:114 GET http://127.0.0.1:8000/static/assets/js/plugins/nouislider.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:123 GET http://127.0.0.1:8000/static/assets/js/plugins/bootstrap-datetimepicker.min.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:126 GET http://127.0.0.1:8000/static/assets/js/photo_swipe/photoswipe.min.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:127 GET http://127.0.0.1:8000/static/assets/js/photo_swipe/photoswipe-ui-default.min.js net::ERR_ABORTED 404 (Not Found)
127.0.0.1/:128 GET http://127.0.0.1:8000/static/assets/js/photo_swipe/init-gallery.js 404 (Not Found)

**Comment by groovemen** [comment]
Hello @nkabram, 

Thank you for using our products, the documentation you can find at the following link: https://demos.creative-tim.com/paper-kit-2-pro/docs/1.0/getting-started/introduction.html and the CSS and JS gives you the error that is missing because of the link that passes through the static folder. Please give us your username of your Creative Tim account to make few checks. Also, please make sure that you have the latest version of the product. 
All the best, 
Stefan
