### ISSUE TITLE
Strange behaviour of dropdown inside card

### ISSUE THREAD

**Issue by gambit4348** [creativetimofficial/ct-paper-kit-2-pro#27]
When Paper KIT 2 PRO css is loaded, DropDown items are presented behind other cards in the same page.

The first image below shows the expected bahaviour of a DropDown in a page with a number of side-by-side cards. In this case, the include for the theme CSS was removed.

![Without Paper-kit](https://user-images.githubusercontent.com/10100737/64083260-24523f80-ccf3-11e9-9150-fa3ecc4628d6.jpg)

The second image below shows the described strange behaviour where DropDown items go behind the other cards in the same page.

![With Paper-kit](https://user-images.githubusercontent.com/10100737/64083261-2a482080-ccf3-11e9-8b81-76c1696293fc.jpg)

I ask for a fix, since this deeply affects the user experience.

Thanks in advance!

Alex

**Comment by groovemen** [comment]
Hello @gambit4348,

Thank you for using our products, I will ask you to share with us a link to your project or to send us the code from the cards from above because I tried to reproduce the issue and it looks good

<img width="450" alt="Screenshot 2019-09-03 at 11 58 17" src="https://user-images.githubusercontent.com/21063398/64159808-70ac9500-ce43-11e9-919d-9282616c54f6.png">

All the best, 
Stefan

**Comment by gambit4348** [comment]
Hello Groovemen, it seems to me that your test case is not exactly my case. You dropdown is no inside a card. The problem happens to me when I have a number of cards and I click to show the dropdown menu of a button inside one of those cards.
If you take a closer look on the imagens I sent, you will notice that the dropdown items being hidden by the cards belong to a button inside the very first card (the one labeled "Pessoa 2").

**Comment by gambit4348** [comment]
Hello Stefan
Sorry, but your instruction did not fix the problem. I took the time to create a test case html page that perfectly demonstrates the issue and, I hope, will help you to spot it more easely. The .ZIP file attached with this post contains all the files to reproduce the situation.
Thanks in advance.
Alex
[Testcase.zip](https://github.com/creativetimofficial/ct-paper-kit-2-pro/files/3609708/Testcase.zip)

**Comment by gambit4348** [comment]
Hello again!
Any news about my issue?
TIA,
Alex

**Comment by groovemen** [comment]
Hello @gambit4348, 

Thank you for using our products, as I told you, please erase the **z-index: 1;** property of the .card and you have to set the **z-index: 1;** for the .card:hover and it will look like this: 

<img width="946" alt="Screenshot 2019-09-26 at 10 16 37" src="https://user-images.githubusercontent.com/21063398/65666648-c2150200-e046-11e9-8b3d-612ac66206ae.png">

All the best, 
Stefan

**Comment by gambit4348** [comment]
Hello Stefan
Bullseye! The issue is fixed!
Thank you so much.
Alex
