### ISSUE TITLE
css issues

### ISSUE THREAD

**Issue by schmidni** [creativetimofficial/ct-paper-kit-2-pro#28]
**Paying for this product I would have hoped it to be a bit more robust, having a ton of issues:**

https://demos.creative-tim.com/paper-kit-2-pro/examples/blog-post.html 
-> author, comments and related articles are missing a "col" class to be displayed correctly on IE

https://demos.creative-tim.com/paper-kit-2-pro/sections.html#blogs
-> huge whitespaces using IE. Cards can be fixed by overwriting the ".card" class from "display:flex" to "display:block" - but I'm not sure why or whether it kills some other layouts.

**On a more general note:** 

css file has a lot of duplicate code, for example sections of the navigation style are in there twice

https://demos.creative-tim.com/paper-kit-2-pro/docs/1.0/getting-started/introduction.html
-> that light grey text on white background kills my eyes, and I have perfect eyesight -.- please be nice to us and change it.

I know IE is a major pain in the arse, but I actually paid that money so I **don't** have to deal with such stuff.

Cheers

**Comment by groovemen** [comment]
Hello @schmidni 

Thank you for using our products, as you can see on our README file, we do not offer Browser Support for then Internet Explorer. Sorry for this inconvenience. 

Hope that information helps you. Please let us know if we can help you with anything else.
All the best, 
Stefan

**Comment by schmidni** [comment]
Never mind that IE is 3rd in market share, but okay, just means your templates are actually not usable in a professional setting. My mistake for not checking first.

The issue of duplicate CSS code and a totally illegible font color on the documentation page remains.

**Comment by groovemen** [comment]
We will proceed to change the text color of the documentation into the next update also, we will get rid of the duplicated code. 
Related to the card property of "**display: flex;**" you can change it into "**display: block;**" by selecting both classes: **.card** & **.card-blog** and it should work without killing other styles/layouts. 

Best, 
Stefan
