### ISSUE TITLE
image being unresponsive on mobile devices

### ISSUE THREAD

**Issue by ryryfingerle** [creativetimofficial/ct-paper-kit-2-pro#29]
1st image: 

<div class="page-header" style="background-image:url('landingpage.png');"
</div>
page-header {
  background-color: #B2AFAB;
  background-position: center center;
  background-size: cover;
  min-height: 100vh; 
  max-height: 999px; 
  height: auto;
  overflow: hidden;
  position: relative;
  width: 100% \9;
  z-index: 1;
}
.page-header .page-header-image {
  position: absolute;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  z-index: -1;
}

2nd image:

<img class="img-responsive center-block" src="../DragonflyDust.png" />

.img-responsive {
  max-width: 100%;
  height: auto;
  display: block;
}

**Comment by ryryfingerle** [comment]
I used the jumbotron code and it works as responsive through mobile but the image becomes center instead of cover the whole screen. On mobile, the image zooms in the center instead of resizing the image to fix the screen. It looks ugly. Am I missing something here? Thanks! 

.jumbotron {
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}

**Comment by groovemen** [comment]
Hello @ryryfingerle,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan

**Comment by ryryfingerle** [comment]
Hi, I’m new to this. I’m sorry that I don’t understand what do you mean by I don’t respected the issue_template? Please let me know. Thanks.

**Comment by groovemen** [comment]
Hello again, 

Firstly, please check if you have the following tag on top of your project:
`<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />`
If it's all good, you can try to set `background-position: center center;` instead of `background-position: center;`. It will be easier for us to find a quick solution if you can send us your entire code.

All the best, 
Stefan
