### ISSUE TITLE
Custom format not working on Datetimepicker

### ISSUE THREAD

**Issue by chongmandick** [creativetimofficial/ct-paper-kit-2-pro#4]
![screen shot 2018-01-31 at 3 05 53 pm](https://user-images.githubusercontent.com/35955783/35609533-a66fb2cc-0698-11e8-9727-e5638c31d978.png)

**Comment by groovemen** [comment]
Hello @chongmandick, thank you for using our templates; if you want a custom format of datetimpicker, you have to initiate it like in the example below:
 ```
$(function () {
    $('#datetimepicker5').datetimepicker({
       defaultDate: "11/1/2018",
       disabledDates: [
           moment("12/25/2018"),
           new Date(2018, 11 - 1, 21),
           "11/22/2013 00:53"
         ]
     });
});
```

Hope this information helps you! 
All the best, 
Stefan
