### ISSUE TITLE
Fonts missing

### ISSUE THREAD

**Issue by akshaybabloo** [creativetimofficial/ct-paper-kit-2-pro#5]
`nucleo-icons.svg` missing in the zip file

**Comment by groovemen** [comment]
Hello @akshaybabloo, thank you for using our product, you will find the required fonts into assets/fonts folder. So please reload the web page(s) and bypass the cache to refresh possibly outdated or corrupted files. Ctrl(Cmd)+Shift+R
Best, Stefan

**Comment by groovemen** [comment]
Hello again @akshaybabloo, if it doesn't work for you, please delete this path: 
`, url('../fonts/nucleo-icons.svg') format('svg');` form the line **10**. 

Best, Stefan

**Comment by ndanielsen** [comment]
Had the same issue.
