### ISSUE TITLE
Multilevel menu

### ISSUE THREAD

**Issue by groovemen** [creativetimofficial/ct-paper-kit-2-pro#6]
If you want a multi-level dropdown menu, this is what you have to do: 
   - create a navbar with a sub-level dropdown menu: 
```
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="https://bootstrapthemes.co" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><a class="dropdown-item dropdown-toggle" href="#">Submenu</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Submenu action</a></li>
                <li><a class="dropdown-item" href="#">Another submenu action</a></li>
                <li><a class="dropdown-item dropdown-toggle" href="#">Subsubmenu</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Subsubmenu action aa</a></li>
                        <li><a class="dropdown-item" href="#">Another subsubmenu action</a></li>
                    </ul>
                </li>
                <li><a class="dropdown-item dropdown-toggle" href="#">Second subsubmenu</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Subsubmenu action bb</a></li>
                        <li><a class="dropdown-item" href="#">Another subsubmenu action</a></li>
                    </ul>
                </li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
```
   - go in `paper-kit.js` and insert this block of code:
```
$( document ).ready( function () {
    $( '.dropdown-menu a.dropdown-toggle' ).on( 'click', function ( e ) {
        var $el = $( this );
        var $parent = $( this ).offsetParent( ".dropdown-menu" );
        if ( !$( this ).next().hasClass( 'show' ) ) {
            $( this ).parents( '.dropdown-menu' ).first().find( '.show' ).removeClass( "show" );
        }
        var $subMenu = $( this ).next( ".dropdown-menu" );
        $subMenu.toggleClass( 'show' );
        
        $( this ).parent( "li" ).toggleClass( 'show' );

        $( this ).parents( 'li.nav-item.dropdown.show' ).on( 'hidden.bs.dropdown', function ( e ) {
            $( '.dropdown-menu .show' ).removeClass( "show" );
        } );
        
         if ( !$parent.parent().hasClass( 'navbar-nav' ) ) {
            $el.next().css( { "top": $el[0].offsetTop, "left": $parent.outerWidth() - 4 } );
        }

        return false;
    } );
} );
```

Best, Stefan

<img width="1438" alt="screen shot 2018-02-26 at 15 22 07" src="https://user-images.githubusercontent.com/21063398/36672987-f9b5b906-1b09-11e8-94f5-4d1b9bf88389.png">

**Comment by krishna-7** [comment]
@groovemen : this is having conflict with the current code. First the drop down will be like : 
![nav1](https://user-images.githubusercontent.com/10972564/36725848-a4be11bc-1bdd-11e8-9ecf-8b62a6b0aa8b.JPG)

Then on clicking the sub menu item name the sub menu drop down moves to the right and it continues like the following. 
![nav2](https://user-images.githubusercontent.com/10972564/36725849-a590f258-1bdd-11e8-8720-fa28979110a7.JPG)
![nav3](https://user-images.githubusercontent.com/10972564/36725850-a5be9c6c-1bdd-11e8-925a-11e8c27ad328.JPG)
![nav4](https://user-images.githubusercontent.com/10972564/36725851-a5f4f686-1bdd-11e8-8e6f-fbfdf2de4e2a.JPG)

![nav5](https://user-images.githubusercontent.com/10972564/36725852-a629cc6c-1bdd-11e8-81a1-913fb9649a51.JPG)

And the sub menus wont hide. Please make sure it doesn't have any conflict with the current code of paper kit 2 pro. 

Cheers!

**Comment by groovemen** [comment]
Hello @krishna-7, 

Please check again and make sure you have all the classes for the navbar from the Paper Kit, also create the dropdown with the sub-level like in the example above because it's working fine, you can see in the photo from the first comment and also in this [video](https://www.dropbox.com/s/1a4qaryowikwpnv/video-1519893626.mp4?dl=0). Make sure you insert the JS code too. Greetings!

**Comment by krishna-7** [comment]
Hi @groovemen,

If you don't mind can you share the entire code of the page that you have shown in the video, because I am still having issues with the multi-level navbar

**Comment by krishna-7** [comment]
Add the following code to _**paper-kit.css**_ along with the above code.

```
.nav-item.dropdown .dropdown-menu li.show .dropdown-menu.show{
  opacity: 1;
  visibility: visible;
}
```

**Comment by groovemen** [comment]
Hello again @krishna-7, sorry for the big delay, here are some changes that you have to make:

- in dropdown.scss file please set display: block; only for the first dropdown because it will affect other submenus. Erase this property from .dropdown-menu class.
```
.dropdown{
  > .dropdown-menu:first-of-type {
    display: block;
  }
}
```
 also set this code to hide those arrows and align the sublevel dropdowns: 
```
.dropdown.show {
  .dropdown-menu.show {
    .dropdown-item.dropdown-toggle + .dropdown-menu {
      &.show {
        left: 166px !important;

        &:before,
        &:after {
          display: none;
        }

        li.show {
          .dropdown-menu.show {
            left: 237px !important;
          }
        }
      }
    }
  }
}

```

Hope this infos helps you!
All the best, Stefan
