### ISSUE TITLE
Responsive design issue

### ISSUE THREAD

**Issue by alec-c4** [creativetimofficial/ct-paper-kit-2-pro#7]
Hi!
I've found following problem with dropdowns in mobile view.
<img width="1833" alt="paper_kit_2_pro_by_creative_tim" src="https://user-images.githubusercontent.com/25312/37390132-ef947974-2777-11e8-8da6-222316c5bbed.png">

**Comment by groovemen** [comment]
Hello @alec-c4, thank you for using our product, please change the `position: absolute` of the `dropdown-menu` from the navbar; you can limit it only for the devices using 
```
@media screen and (max-width: 991px) {
    position: relative;
}
```
Hope it's useful!
Best, Stefan
