### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by alec-c4** [creativetimofficial/ct-paper-kit-2-pro#9]
Hi!
Please check console at https://demos.creative-tim.com/paper-kit-2-pro/examples/register.html
You'll see that 

```
Mixed Content: The page at 'https://demos.creative-tim.com/paper-kit-2-pro/examples/register.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.
```

It means that you need to update links in head section to https

**Comment by groovemen** [comment]
Hello @alec-c4, thank you for using our templates, we appreciate your vigilant eye and for letting us know about the issue, this will be solved in the next update!

All the best, 
Stefan
